sonar.projectKey=mauriceabadoma-commits_archiva-api
sonar.organization=mauriceabadoma-commits

sonar.sources=src,api,includes,config
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml

sonar.exclusions=vendor/**,coverage-html/**